config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :habits
  #get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, uniqueness: { case_sensitive: true }
	belongs_to :user
end

app/models/habit.rb
class Habit < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :habits
         has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully edited." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :set_habit, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /habits or /habits.json
  def index
    if params[:search]
      @habits = Habit.where(date: params[:search])
    else 
      @habits = Habit.where(date: Date.today)
    end
  end

  # GET /habits/1 or /habits/1.json
  def show
  end

  # GET /habits/new
  def new
    @habit = Habit.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits or /habits.json
  def create
    @habit = Habit.new(habit_params)

    respond_to do |format|
      if @habit.save
        format.html { redirect_to habits_path, notice: "Log was successfully added." }
        format.json { render :show, status: :created, location: @habit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1 or /habits/1.json
  def update
    respond_to do |format|
      if @habit.update(habit_params)
        format.html { redirect_to habits_path, notice: "Log was successfully edited." }
        format.json { render :show, status: :ok, location: @habit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @habit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1 or /habits/1.json
  def destroy
    @habit.destroy
    respond_to do |format|
      format.html { redirect_to habits_url, notice: "Log was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_habit
      @habit = Habit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def habit_params
      params.require(:habit).permit(:date, :category, :hours, :minutes, :description, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  
  <div class="justify-content-center my-2" id="input_form">
    <% if category.errors.any? %>
      <div class="error_explanation alert alert-danger alert-dismissible fade show m-0 p-0" role="alert">
      <p class="mb-0">
        <ul class="m-0 p-0">
          <% category.errors.each do |error| %>
            <p class="p-0 m-2">Error! <%= error.full_message %></p>
          <% end %>
        </ul></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>

    <div class="field form-group my-3">
      <%= form.label :name, class:"font-weight-bold d-flex" %>
      <%= form.text_field :name, class:"form-control" %>
    </div>

    <%= form.number_field :user_id, id: :category_user_id,value: current_user.id, type: :hidden %>

    <div class="actions d-flex my-2">
      <%= form.submit class:'btn btn-info btn-block'%>
    </div>
    <div class="actions d-flex my-2">
      <%=link_to 'Cancel', :back, class:'btn btn-outline-info btn-block' %>
    </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h2 class="text-center">Edit Category</h2>

<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h2 class="text-center">Categories</h2>

<div class="d-flex flex-row-reverse">
   <!-- Add new log -->
  <div class="my-3">
    <%= link_to 'Add', new_category_path, class:"btn btn-info" %>
  </div>
</div>

<div id="table_container  mt-2">
  <table class="table table-bordered text-center table-hover shadow" id="habits_table">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <% if category.user == current_user %>
          <tr>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', edit_category_path(category) %></td>
            <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<h2 class="text-center">Add New Category</h2>

<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/habits/_form.html.erb
<%= form_with(model: habit) do |form| %>
  <div class="justify-content-center my-2" id="input_form">
    <% if habit.errors.any? %>
      <div class="error_explanation alert alert-danger alert-dismissible fade show m-0 p-0" role="alert">
      <p class="mb-0">
        <ul class="m-0 p-0">
          <% habit.errors.each do |error| %>
            <p class="p-0 m-2">Error! <%= error.full_message %></p>
          <% end %>
        </ul></p>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <% end %>

    <div class="field form-group">
      <%= form.label :date, class:"font-weight-bold" %></br>
      <%= form.date_field :date , order: [:day, :month, :year], max: Date.today, value: Date.today, required: true%>
    </div>

    <div class="field form-group">
      <%= form.label :category, class:"font-weight-bold d-flex" %>
      <%= form.select(:category, current_user.categories.collect { |category| [category.name] }) %>
      <%= link_to "Add new category", new_category_path, class:"nav-link p-0 mt-2" %>
    </div>

    <div class="form-group">
      <p , class="font-weight-bold mb-0">Duration</p>
      <div class="row">
        <div class="field col">
          <%= form.label :hours %>
          <%= form.number_field :hours, class:"form-control flex-grow-1", value: 0, max: 23, min:0, required: true %>
        </div>
        <div class="field col">
          <%= form.label :minutes %>
          <%= form.number_field :minutes, class:"form-control flex-grow-1",  value: 0, max: 59, min:0,  required: true %>
        </div> 
      </div>
    </div>

    <div class="field form-group">
      <%= form.label :description, class:"font-weight-bold" %>
      <%= form.text_field :description, class:"form-control", maxlength:50 %>
    </div>

    <%= form.number_field :user_id, id: :habit_user_id,value: current_user.id, type: :hidden %>

    <div class="actions d-flex my-2">
      <%= form.submit class:'btn btn-info btn-block'%>
    </div>
    <div class="actions d-flex my-2">
      <%= link_to 'Cancel', habits_path, class:'btn btn-outline-info btn-block'%>
    </div>
  </div>
<% end %>

app/views/habits/edit.html.erb
<h2 class="text-center">Edit Log</h2>

<%= render 'form', habit: @habit %>

app/views/habits/index.html.erb
<h2 class="text-center">Tracker</h2>

<div class="d-flex justify-content-between">
  <!-- Search by date -->
  <div class="field form-group">
  <%= form_tag habits_path, method: :get do %>
    <%= label_tag  "Change date:" %></br>
    <%= date_field_tag :search, params[:search], max: Date.today %>
    <%= submit_tag "Search" %>
  <% end %>
  </div>

  <!-- Add new log -->
  <div class="my-auto">
    <%= link_to 'Add', new_habit_path, class:"btn btn-info" %>
  </div>
</div>

<!-- Habits table-->
<div id="table_container  mt-2">
<table class="table table-bordered text-center table-hover shadow" id="habits_table">
  <thead class="thead-dark">
    <tr>
      <th>Category</th>
      <th>Duration</th>
      <th>Description</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @habits.each do |habit| %>
      <% if habit.user == current_user %>
        <tr>
          <td><%= habit.category %></td>
          <td><%= habit.hours %> hr <%= habit.minutes %> min</td>
          <td><%= habit.description %></td>
          <td><%= link_to 'Edit', edit_habit_path(habit) %></td>
          <td><%= link_to 'Delete', habit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/habits/new.html.erb
<h2 class="text-center">Add New Log</h2>

<%= render 'form', habit: @habit %>

app/views/habits/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @habit.date %>
</p>

<p>
  <strong>Category:</strong>
  <%= @habit.category %>
</p>

<p>
  <strong>Hours:</strong>
  <%= @habit.hours %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @habit.minutes %>
</p>

<p>
  <strong>Description:</strong>
  <%= @habit.description %>
</p>

<%= link_to 'Edit', edit_habit_path(@habit) %> |
<%= link_to 'Back', habits_path %>

app/views/home/_header.html.erb
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "GoodHabs", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
        <%= link_to "Tracker", habits_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Log out<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/home/index.html.erb
<div class="text-center">
	<h1 class="p-0 m-0">GoodHabs</h1>
	<p>The positive habits tracker</p>
</div>

<div class="row p-3 shadow mt-4" >
	<div class="col-lg-9 col-12 text-justify  my-auto pb-2">
		<h2 class="text-center"> What is GoodHabs?</h2>
		GoodHabs is a tiny web app where you can keep track of your daily positive habits. Here you'll be able to create the <strong>Categories</strong> that fit your needs (such as Exercising, Reading, Meditate, etc.) and log your daily activities to each one of them. This logs will be stored in the app and you can easily access them by date in the <strong>Tracker</strong> view.
	</div>
	<div class="col-lg-3 col-12 d-flex justify-content-center mt-2 my-auto">
				<img
				width=300px
				height=250px
				class="rounded-circle p-2"
				src="https://images.pexels.com/photos/936094/pexels-photo-936094.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"
						/>
	</div>
</div>
<div class="row mt-3 d-flex justify-content-between">
	<div class="col-lg-6 col-12 text-justify shadow my-3">
		<h2 class="text-center mt-4">Functionalities</h2>
		<div class="mx-auto mt-3">
			<ul>
				<li>Add categotegories</li>
				<li>Add daily logs (yes, you can add on previous days too)</li>
				<li>Search by date</li>
				<li>Sign up</li>
				<li>Log in</li>
			</ul>
		</div>
	</div>
	<div class="col-lg-5 col-12 text-justify shadow my-3">
		<h2 class="text-center mt-4">Quick Start</h2>
		<div class="mx-auto mt-3">
			<ul>
				<li>Do you want to keep track of your habits?</li>
				<li>Register an account <!-- link register--></li>
				<li>Now is time to log in<!-- link login--></li>
				<li>Create the categories you'll use</li>
				<li>Track your activities</li>
				<li>Achieve your goals</li>
			</ul>
		</div>
	</div>
</div>
					
					
		

app/views/layouts/_alerts.html.erb
<!-- Alerts for notice -->
<div class="alert alert-info alert-dismissible fade show mt-2" role="alert">
  <%= notice or exception %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_header.html.erb
<!-- Nav Bar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "GoodHabs", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Tracker", habits_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", edit_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in",  new_user_session_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <title>GoodHabs</title>

    <!-- ROR setup -->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Application body --> 
    <%= render 'layouts/header' %>

    <div class="container mt-3">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>  

      <%= yield %>
    </div>

    <!-- Bootstrap tags --> 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>